---
title: "ms_2"
author: "Raymond Hu"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sophia Zheng- Housing Explorations in US Areas of Interest

This project analyzes price statistics in three major metropolitan areas in the USA: New York Ctiy, San Francisco, and Seattle. Starting with the pros, 

Pros:
Within each metric, trends in data are easy to identify. For example, immediately you can tell the drop in prices began after 2008, which makes intuitive sense. Keeping the analysis to only three metropolitan areas make the graphs easy to comprehend and intepret. Further, Sophia does a good job comprehensively including multiple metrics on which you can evaluate the cost of living in each area.It seems as though she had to source and clean data for a multitude of sources.


Cons:
Wtihin the first "Explore" tab, the drop down list of Housing Price comparisons ony allows you to view one graph at a time, making cross criteria comparisons a bit difficult. I think it would have been better to include an option where you can directly compare them. Furthermore, the axes limits and scales for some of the graphs differ so as you are switching between them, it is even more difficult to compare. On the topic of comparison, underneath the "Income and Housing Value Comparisons" tab, Sophia created an animated graph showing the average Zillow Home Value Index vs. Median income over time. While interesting to look at, it is a bit difficult trying to track the changes in its relationship because the time moves so quickly and is not labeled in a conspicuous way. 

## Jackson Kehoe - Orchids Around the World

This project analyzes the distribution of orchids around the world. 

Pros: 
The data for each country and year is grouped well. It's very easy to make cross country comparisons. The data also highlights the disparity between importer reported specimens and exporter reported specimens- an interesting area in which I would be curious to explore more.

Cons:
It would have been even better if there was a way to see a comparison of orchid distribution across time, rather than just within a select year for the data in "Importers 1".The final tab, "Threats", is a little confusing and I"m not sure what meaningful insights can be extrapolated from the word clouds. I don't think word clouds are an effective medium for conveying useful information since the keywords are so disparate and there is no context provided. Within the "Importers 2" tab, I'm not sure I totally understand what this graph is trying to convey either. The variables seem a little convoluted.

Links: 
https://github.com/ryzhu75/ms_2.git
https://github.com/ryzhu75/ms_2


